export const SEGURADORAS = [
  'Porto Seguro',
  'SulAmérica',
  'Bradesco Seguros',
  'Itaú Seguros',
  'Mapfre',
  'Allianz Seguros',
  'Zurich Seguros',
  'HDI Seguros',
  'Liberty Seguros',
  'Tokio Marine',
  'AIG Seguros',
  'Chubb',
  'BB Seguridade',
  'Icatu Seguros',
  'Mongeral Aegon',
  'Sompo Seguros',
  'Generali Brasil',
  'AXA Seguros',
  'Capemisa Seguradora',
  'PAN Seguros',
  'Cardif',
  'Mitsui Sumitomo',
  'Azul Seguros',
  'Previsul',
  'Indiana Seguros',
  'Excelsior Seguros',
  'Nobre Seguradora',
  'Sancor Seguros',
  'Argo Seguros',
  'Berkley Brasil',
  'Markel Seguros',
  'QBE Seguros',
  'Austral Seguradora',
  'Junto Seguros',
  'Youse Seguros',
  'Kovr Seguros',
  'Porto Saúde',
  'SulAmérica Saúde',
  'Bradesco Saúde',
  'Amil',
  'Hapvida',
  'Notre Dame Intermédica',
  'Golden Cross',
  'Omint',
  'Prevent Senior',
  'São Francisco Saúde',
  'Seguros Unimed',
  'Unimed Nacional',
  'MetLife',
  'Prudential do Brasil',
] as const

export type Seguradora = (typeof SEGURADORAS)[number]
