'use server'
import { redirect } from 'next/navigation'
import { createAdminClient } from '@/lib/supabase/admin'
import { createClient } from '@/lib/supabase/server'
import { inviteSchema, acceptInviteSchema, type FormError } from '@/lib/validations/auth-schemas'

// ---------------------------------------------------------------------------
// Internal helper — reads JWT claims and enforces admin role
// ---------------------------------------------------------------------------
async function requireAdmin(): Promise<{ uid: string; tenant_id: string; slug?: string }> {
  const supabase = await createClient()

  const anySupa = supabase.auth as unknown as {
    getClaims?: () => Promise<{
      data: {
        claims: {
          sub?: string
          app_metadata?: { tenant_id?: string; role?: string; slug?: string }
        } | null
      } | null
    }>
  }

  let uid: string | undefined
  let tenant_id: string | undefined
  let role: string | undefined
  let slug: string | undefined

  if (typeof anySupa.getClaims === 'function') {
    const { data } = await anySupa.getClaims()
    uid = data?.claims?.sub
    tenant_id = data?.claims?.app_metadata?.tenant_id
    role = data?.claims?.app_metadata?.role
    slug = data?.claims?.app_metadata?.slug
  } else {
    const { data } = await supabase.auth.getUser()
    uid = data.user?.id
    const meta = data.user?.app_metadata as
      | { tenant_id?: string; role?: string; slug?: string }
      | undefined
    tenant_id = meta?.tenant_id
    role = meta?.role
    slug = meta?.slug
  }

  if (!uid || !tenant_id || role !== 'admin') {
    throw new Error('FORBIDDEN')
  }

  return { uid, tenant_id, slug }
}

// ---------------------------------------------------------------------------
// inviteUser — admin sends email invite, inserts user_invitations row
// ---------------------------------------------------------------------------
export async function inviteUser(
  formData: FormData,
): Promise<{ error?: FormError; invitationId?: string } | void> {
  let ctx: { uid: string; tenant_id: string; slug?: string }
  try {
    ctx = await requireAdmin()
  } catch {
    return { error: { _form: ['Apenas administradores podem convidar usuários.'] } }
  }

  const parsed = inviteSchema.safeParse(Object.fromEntries(formData))
  if (!parsed.success) {
    return { error: parsed.error.flatten().fieldErrors as FormError }
  }
  const { email, role } = parsed.data

  const admin = createAdminClient()

  // Idempotent: cancel any non-accepted pending invite for same email+tenant
  await admin
    .from('user_invitations')
    .update({ cancelled_at: new Date().toISOString() })
    .eq('tenant_id', ctx.tenant_id)
    .eq('email', email)
    .is('accepted_at', null)
    .is('cancelled_at', null)

  // INSERT new invite — token generated by DB DEFAULT encode(gen_random_bytes(32),'hex')
  const { data: invite, error: insertErr } = await admin
    .from('user_invitations')
    .insert({
      tenant_id: ctx.tenant_id,
      email,
      role,
      invited_by: ctx.uid,
    })
    .select('id, token')
    .single()

  if (insertErr || !invite) {
    return { error: { _form: ['Erro ao criar convite. Tente novamente.'] } }
  }

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000'
  const { error: mailErr } = await admin.auth.admin.inviteUserByEmail(email, {
    redirectTo: `${appUrl}/convite/${invite.token}`,
  })

  if (mailErr) {
    // Rollback — mark invite cancelled
    await admin
      .from('user_invitations')
      .update({ cancelled_at: new Date().toISOString() })
      .eq('id', invite.id)
    return {
      error: {
        _form: ['Não foi possível enviar o convite por e-mail. Tente novamente.'],
      },
    }
  }

  return { invitationId: invite.id }
}

// ---------------------------------------------------------------------------
// resendInvite — admin-only; extends expiry 72h and resends email
// ---------------------------------------------------------------------------
export async function resendInvite(
  invitationId: string,
): Promise<{ error?: string } | void> {
  let ctx: { tenant_id: string }
  try {
    ctx = await requireAdmin()
  } catch {
    return { error: 'Apenas administradores podem reenviar convites.' }
  }

  const admin = createAdminClient()
  const { data: invite, error } = await admin
    .from('user_invitations')
    .update({
      expires_at: new Date(Date.now() + 72 * 3600 * 1000).toISOString(),
    })
    .eq('id', invitationId)
    .eq('tenant_id', ctx.tenant_id)
    .is('accepted_at', null)
    .is('cancelled_at', null)
    .select('email, token')
    .single()

  if (error || !invite) {
    return { error: 'Convite não encontrado ou já processado.' }
  }

  const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000'
  const { error: mailErr } = await admin.auth.admin.inviteUserByEmail(invite.email, {
    redirectTo: `${appUrl}/convite/${invite.token}`,
  })

  if (mailErr) {
    return { error: 'Erro ao reenviar e-mail de convite.' }
  }
}

// ---------------------------------------------------------------------------
// cancelInvite — admin-only; sets cancelled_at on the invite
// ---------------------------------------------------------------------------
export async function cancelInvite(
  invitationId: string,
): Promise<{ error?: string } | void> {
  let ctx: { tenant_id: string }
  try {
    ctx = await requireAdmin()
  } catch {
    return { error: 'Apenas administradores podem cancelar convites.' }
  }

  const admin = createAdminClient()
  const { error } = await admin
    .from('user_invitations')
    .update({ cancelled_at: new Date().toISOString() })
    .eq('id', invitationId)
    .eq('tenant_id', ctx.tenant_id)
    .is('accepted_at', null)
    .is('cancelled_at', null)

  if (error) {
    return { error: 'Erro ao cancelar convite.' }
  }
}

// ---------------------------------------------------------------------------
// acceptInvite — validates token atomically, sets password, creates profile,
//               auto-logs in and redirects to /{slug}/dashboard
// ---------------------------------------------------------------------------
export async function acceptInvite(
  token: string,
  formData: FormData,
): Promise<{ error?: string } | void> {
  const parsed = acceptInviteSchema.safeParse(Object.fromEntries(formData))
  if (!parsed.success) {
    const flat = parsed.error.flatten()
    const first = Object.values(flat.fieldErrors).flat()[0] ?? 'Dados inválidos'
    return { error: first }
  }
  const { fullName, password } = parsed.data

  const admin = createAdminClient()

  // ATOMIC single-use claim — UPDATE returns the row only when all three guards pass:
  //   1. accepted_at IS NULL  (not already used)
  //   2. cancelled_at IS NULL (not cancelled)
  //   3. expires_at > NOW()   (not expired)
  const { data: invite, error: claimErr } = await admin
    .from('user_invitations')
    .update({ accepted_at: new Date().toISOString() })
    .eq('token', token)
    .is('accepted_at', null)
    .is('cancelled_at', null)
    .gt('expires_at', new Date().toISOString())
    .select('id, tenant_id, email, role, tenants(id, slug, name)')
    .single()

  if (claimErr || !invite) {
    return {
      error:
        'Este link de convite já foi utilizado ou expirou. Faça login se já tiver uma conta.',
    }
  }

  // Find the auth user that inviteUserByEmail pre-created
  const { data: listRes } = await admin.auth.admin.listUsers()
  const authUser = listRes?.users?.find(
    (u) => u.email?.toLowerCase() === invite.email.toLowerCase(),
  )
  if (!authUser) {
    return {
      error:
        'Usuário do convite não encontrado. Peça para o administrador reenviar o convite.',
    }
  }

  const tenantSlug = (invite.tenants as { slug: string } | null)?.slug
  if (!tenantSlug) {
    return { error: 'Corretora não encontrada.' }
  }

  // Set password + app_metadata (app_metadata only — never user_metadata for tenant_id/role)
  const { error: updErr } = await admin.auth.admin.updateUserById(authUser.id, {
    password,
    email_confirm: true,
    app_metadata: {
      tenant_id: invite.tenant_id,
      role: invite.role,
      slug: tenantSlug,
    },
    user_metadata: { full_name: fullName },
  })
  if (updErr) {
    return { error: 'Erro ao ativar conta. Tente novamente.' }
  }

  // Create profile
  const { error: profErr } = await admin.from('profiles').upsert({
    id: authUser.id,
    tenant_id: invite.tenant_id,
    full_name: fullName,
    role: invite.role,
    active: true,
  })
  if (profErr) {
    return { error: 'Erro ao criar perfil. Tente novamente.' }
  }

  // Auto-login via SSR client so session cookies are set
  const supabase = await createClient()
  const { error: signInErr } = await supabase.auth.signInWithPassword({
    email: invite.email,
    password,
  })
  if (signInErr) {
    redirect(`/login?next=/${tenantSlug}/dashboard`)
  }

  redirect(`/${tenantSlug}/dashboard`)
}
